import copy
import unittest

import numpy as np

from dynamics_manual_steps import (manual_step_report, predict_particles2, runtime_parameters,
                                   synthetic_contract, synthetic_manual_capture, unity_matrix)
from dynamics_motion_replay import synthetic_capture


class DynamicsManualStepsTests(unittest.TestCase):
    def setUp(self):
        # Synthetic intermediates only: generated by the oracle itself, no private data.
        self.capture = synthetic_manual_capture(manual_frames=(2, 5))
        self.contract = synthetic_contract()

    def components(self, report):
        return {row['rootName']: row for frame in report['frames'] for row in frame['components']}

    def test_unity_matrix_reads_the_column_major_serialization(self):
        flat = list(range(16))
        matrix = unity_matrix(flat)
        self.assertEqual(matrix.shape, (4, 4))
        # The fixture writes m00,m10,m20,m30,m01,...: the translation is the last four floats.
        self.assertEqual([float(value) for value in matrix[:3, 3]], [12.0, 13.0, 14.0])
        self.assertEqual(float(matrix[1, 0]), 1.0)

    def test_predict_particles2_reproduces_the_oracle_generated_intermediates(self):
        report = manual_step_report(self.capture, self.contract, 1e-4)
        self.assertTrue(report['passed'])
        self.assertEqual([frame['frame'] for frame in report['frames']], [2, 5])
        # The synthetic afterParticles2 come from the same float32 method, so
        # the re-prediction from the recorded inputs must be bit-exact.
        self.assertEqual(report['maxResidual'], 0.0)
        # afterParticles2 and the recorded frame-end internalPosition were
        # written from the same positions dict in the generator.
        self.assertEqual(report['maxOfficialDelta'], 0.0)
        self.assertEqual(self.components(report)['root']['maxResidual'], 0.0)

    def test_ablating_the_collider_rows_refutes_the_prediction(self):
        report = manual_step_report(self.capture, self.contract, 1e-4)
        row = self.components(report)['root']
        # Without the recorded collider rows the prediction leaves the capsule
        # where it entered, so the residual jumps by centimeters while the
        # with-collider prediction stays exact.
        self.assertEqual(row['maxResidual'], 0.0)
        self.assertGreater(row['maxResidualWithoutColliders'], 1e-2)
        pushes = {push['particle']: push['push'] for push in row['colliderPushes']}
        self.assertIn('middle', pushes)
        self.assertGreater(pushes['middle'], 1e-4)

    def test_children_follow_the_parents_updated_position_not_its_p1_value(self):
        # Mutating one post-UpdateParticles1 root position must move every
        # descendant's prediction, because UpdateParticles2 projects each
        # particle onto the parent's CURRENT m_Position (written back by the
        # same method), not its input value.
        shifted = copy.deepcopy(self.capture)
        step = shifted['frames'][2]['components'][0]['manualSteps'][0]
        for row in step['afterParticles1']:
            if row['name'] == 'root':
                row['position'][0] += .02
        parameters, weight = runtime_parameters(shifted['components'][0])
        frame_row = shifted['frames'][2]
        baseline = predict_particles2(self.capture['frames'][2]['components'][0]['manualSteps'][0],
            frame_row['colliders'], parameters, weight, 1.0)
        moved = predict_particles2(step, frame_row['colliders'], parameters, weight, 1.0)
        for name in ('middle', 'tip', 'branch'):
            delta = float(np.linalg.norm(moved[name] - baseline[name]))
            self.assertGreater(delta, 1e-3, name)
        self.assertAlmostEqual(float(np.linalg.norm(moved['root'] - baseline['root'])), .02, delta=1e-6)

    def test_runtime_parameters_match_the_contract_within_float_round_trip(self):
        report = manual_step_report(self.capture, self.contract, 1e-4)
        parameters = report['runtimeParameters']
        self.assertEqual(parameters['runtimeOffContract'], [])
        self.assertLess(parameters['maxRuntimeContractDelta'], 1e-6)
        # The synthetic contract keeps the definition's stiffness values; a
        # runtime m_Stiffness of 1 (radius-zero hypothesis) would show here.
        self.assertAlmostEqual(parameters['maxRuntimeStiffness'], .3, delta=1e-6)
        self.assertTrue(parameters['runtimeStableAcrossFrames'])

    def test_capture_without_manual_steps_is_refused(self):
        with self.assertRaisesRegex(ValueError, 'manualSteps'):
            manual_step_report(synthetic_capture(frames=4))

    def test_parent_block_spread_and_avatar_matrix_agree_on_the_synthetic_frame(self):
        # The synthetic bones keep identity world rotations, so every recorded
        # parentMatrix block is identity and matches the avatar rotation times
        # the preamble objectScale exactly.
        report = manual_step_report(self.capture, self.contract, 1e-4)
        for frame in report['frames']:
            self.assertEqual(frame['maxParentBlockSpread'], 0.0)
            self.assertEqual(frame['maxAvatarBlockDelta'], 0.0)


if __name__ == '__main__':
    unittest.main()
