import copy
import unittest

import numpy as np

from dynamics_motion_replay import compare, distance, frame, orientation, synthetic_capture, synthetic_document


class DynamicsMotionReplayTests(unittest.TestCase):
    def setUp(self):
        # Synthetic capture only: generated by the oracle itself, no private data.
        self.capture = synthetic_capture(frames=12)
        self.document = synthetic_document()

    def test_space_conversion_is_the_document_z_mirror_involution(self):
        self.assertEqual(frame([1, 2, 3]), [1.0, 2.0, -3.0])
        self.assertEqual(frame(frame([1.5, -.25, .75])), [1.5, -.25, .75])
        # Only the negated x,y components run through float32; z,w pass through.
        f = np.float32
        self.assertEqual(orientation([.1, .2, .3, .4]), [-float(f(.1)), -float(f(.2)), .3, .4])
        self.assertEqual(orientation(orientation([.1, .2, .3, .4])), [float(f(.1)), float(f(.2)), .3, .4])

    def rows(self, result):
        return {row['model']: row for row in result['components']}

    def test_exact_replay_of_the_oracle_generated_capture_has_zero_error(self):
        result = compare(self.capture, self.document)
        self.assertTrue(result['passed'])
        self.assertEqual(result['frameCount'], 12)
        rows = self.rows(result)
        self.assertEqual(len(result['components']), 2)  # both models per component
        diagnostic = rows['bind-hierarchy diagnostic']
        self.assertEqual(diagnostic['maxParticleError'], 0)
        self.assertEqual(diagnostic['maxRootPosition'], 0)
        self.assertEqual(diagnostic['maxColliderRigidity'], 0)
        recorded = rows['recorded inputs']
        # The recorded world rotations go through a float32 matrix ->
        # quaternion -> matrix round-trip, so exactness holds only to float32
        # noise, far below the 1e-4 gate.
        self.assertLess(recorded['maxParticleError'], 1e-6)
        self.assertEqual(recorded['particles'], 4)
        self.assertEqual(recorded['stepCounts'], dict(min=1, max=1))
        self.assertAlmostEqual(recorded['restOffsetBindRatio'], 1.0, delta=1e-5)
        self.assertEqual(recorded['firstExceeded'], None)

    def test_recorded_particle_deviation_is_reported_with_its_frame(self):
        capture = copy.deepcopy(self.capture)
        capture['frames'][5]['components'][0]['particles'][2]['position'][0] += .003
        result = compare(capture, self.document)
        self.assertFalse(result['passed'])
        self.assertAlmostEqual(result['maxParticleError'], .003, delta=1e-6)
        self.assertEqual(result['worstFrame'], 5)

    def test_recorded_root_is_an_input_while_the_bind_model_flags_rigidity(self):
        capture = copy.deepcopy(self.capture)
        capture['frames'][7]['components'][0]['root']['position'][0] += .004
        capture['frames'][7]['components'][0]['colliders'][0]['position'][2] -= .002
        result = compare(capture, self.document)
        rows = self.rows(result)
        # In the bind-hierarchy model the recorded root/collider transforms are
        # predictions, so particle parity holds while rigidity flags fire.
        diagnostic = rows['bind-hierarchy diagnostic']
        self.assertLess(diagnostic['maxParticleError'], 1e-6)
        self.assertGreater(diagnostic['maxRootPosition'], .003)
        self.assertGreater(diagnostic['maxColliderRigidity'], .001)
        # In the recorded-input model the root position is an integrator input:
        # particle 0 is reset onto the shifted root the same step, so the
        # fabricated shift is reported as parity failure on that frame.
        recorded = rows['recorded inputs']
        self.assertGreater(recorded['maxParticleError'], .003)
        self.assertGreaterEqual(recorded['firstExceeded']['frame'], 7)
        self.assertFalse(result['passed'])

    def test_two_frame_recorded_replay_matches_the_oracle(self):
        # Expected positions come from the oracle itself: the capture was
        # produced by advancing the same solver through recorded inputs, so a
        # recorded-input replay of the two frames reproduces them to float32
        # rotation round-trip noise.
        capture = synthetic_capture(frames=2)
        result = compare(capture, synthetic_document())
        self.assertTrue(result['passed'])
        self.assertLess(self.rows(result)['recorded inputs']['maxParticleError'], 1e-6)

    def test_identity_and_shape_mismatches_are_refused(self):
        variants = []
        changed = copy.deepcopy(self.capture)
        changed['frames'][2]['components'][0]['particles'][1]['name'] = 'other'
        variants.append(changed)
        changed = copy.deepcopy(self.capture)
        changed['frameCount'] = 11
        variants.append(changed)
        changed = copy.deepcopy(self.capture)
        changed['components'][0]['particles'].pop()
        variants.append(changed)
        changed = copy.deepcopy(self.capture)
        changed['frames'][3]['components'].append(changed['frames'][3]['components'][0])
        variants.append(changed)
        for changed in variants:
            with self.assertRaises(ValueError):
                compare(changed, self.document)

    def test_contract_disabled_collider_refutes_the_motion_model(self):
        # The original capture enables every recorded hair collider; a contract
        # that replays one as disabled is a different integrator.
        document = copy.deepcopy(self.document)
        document['scenarios'][0]['definition']['colliders'][0]['enabled'] = False
        with self.assertRaises(ValueError):
            compare(self.capture, document)

    def test_replay_follows_the_seed_weight_and_locked_accumulator(self):
        document = copy.deepcopy(self.document)
        document['scenarios'][0]['definition']['updateRate'] = 30
        capture = copy.deepcopy(self.capture)
        capture['components'][0]['weight'] = .5
        result = compare(capture, document)
        # Same seed, different rate: the recorded 60 Hz trajectory cannot be
        # reproduced by a 30 Hz contract replay at weight .5.
        self.assertFalse(result['passed'])
        self.assertGreater(result['maxParticleError'], 1e-4)

    def test_distance_matches_float32_norm(self):
        self.assertEqual(distance([0, 0, 0], [.001, 0, 0]), float(np.float32(.001)))


if __name__ == '__main__':
    unittest.main()
